# EDS 232 Kaggle Competition (2026)
Authors: Melannie Moreno Rolon, Ixel Medrano, Vedika Shirtekar

## Background
This needs a markdown section that explains what the notebook contains and the data being used.

## Setup (5 pts)
load your libraries and read in the data.

In [ ]:
# Import relevant libraries
import pandas as pd # For data manipulation and analysis
import matplotlib.pyplot as plt # For plotting and visualization
import sklearn as sk # Machine learning library (scaling, standardization, etc.)
import numpy as np # For numerical operations

Luckily, our train and test sets are separated, so we don't have to worry about splitting our data.

In [9]:
# Import train and test sets
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [10]:
# Show the first few rows of the training data
train.head()

   id  CTDTEMP_ITS90  Salinity_PSS78  Depth      TA     DIC
0   0          15.36         33.6095   10.0  2241.0  1989.4
1   1          11.23         33.6095   10.0  2241.0  1989.8
2   2          11.23         33.6095   10.0  2241.0  1989.3
3   3          11.23         33.6095   10.0  2241.0  1988.6
4   4          15.06         33.2820   10.0  2241.0  1991.5

In [15]:
# Store features in an array to extract
features = ["CTDTEMP_ITS90", "TA", "Salinity_PSS78", "Depth"]
features 

# Extract from train and store as X and y
X_train =  train[features]
y_train = train["DIC"]

## Exploratory Data Analysis (35) pts
explore the features and target: distributions, relationships, and anything that may inform your modeling choices. Include at least one visualization

We will explore properties of the features (`X_train`) and target/outcome (`y_train`).

In [17]:
# What does X_train contain? 
X_train.head() # It is a df with all features except DIC

   CTDTEMP_ITS90      TA  Salinity_PSS78  Depth
0          15.36  2241.0         33.6095   10.0
1          11.23  2241.0         33.6095   10.0
2          11.23  2241.0         33.6095   10.0
3          11.23  2241.0         33.6095   10.0
4          15.06  2241.0         33.2820   10.0

## Models (25 pts) 
fit at least two different models, each with a hyperparameter search grid (if applicable), showing your tuning process and how you select the best configuration.

## Summary (25 pts)
compare your models' results side by side and comment on them: which performed best, why you think that is, and which model you decided to go with.